"use client";
import React, { useState, useEffect } from "react";
import styles from "./page.module.css";
import Image from "next/image";
import Head from "next/head";
import Generador from "@/components/generador/generador";
import Header from "@/components/header/header";
import Intro from "@/components/intro/intro";

export default function Home() {
  const [loadingIntro, setLoadingIntro] = useState(true);

  useEffect(() => {
    const timer = setTimeout(() => {
      setLoadingIntro(false);
    }, 3300);

    return () => clearTimeout(timer);
  }, []);

  return (
    <>
      <Head>
        <title>Walkeriano</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        {loadingIntro ? (
          <>
            <Intro />
          </>
        ) : (
          <section className={styles.flexOperation}>
            <Header />
            <Generador />
          </section>
        )}
        <div className={styles.texture}>
          <Image src="/texture.svg" alt="bg-texture" fill={true} />
        </div>
        <div className={styles.textureTwo}>
          <Image src="/textureTwo.svg" alt="bg-texture" fill={true} />
        </div>
        <div className={styles.degrad}></div>
      </main>
    </>
  );
}
